Number1 = int(input("Please Select Fist Number : "))
Number2 = int(input("Please Select Last Number : "))
print(Number1,"+",Number2,"=",Number1 + Number2)
print(Number1,"-",Number2,"=",Number1 - Number2)
print(Number1,"X",Number2,"=",Number1 * Number2)
print(Number1,"/",Number2,"=",Number1 / Number2)